// Code generated by protoc-gen-go. DO NOT EDIT.
// source: item.proto

/*
Package model is a generated protocol buffer package.

It is generated from these files:
	item.proto

It has these top-level messages:
	Server
	Item
	Items
	KeyIDPair
	KeyIDPairs
	StampedKey
	Index
	IndexMap
	DataResponse
*/
package model

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"
import google_protobuf1 "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Server struct {
	Id      string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Address string `protobuf:"bytes,2,opt,name=address" json:"address,omitempty"`
}

func (m *Server) Reset()                    { *m = Server{} }
func (m *Server) String() string            { return proto.CompactTextString(m) }
func (*Server) ProtoMessage()               {}
func (*Server) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Server) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Server) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type Item struct {
	Data      []byte                     `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Key       string                     `protobuf:"bytes,2,opt,name=key" json:"key,omitempty"`
	Timestamp *google_protobuf.Timestamp `protobuf:"bytes,3,opt,name=timestamp" json:"timestamp,omitempty"`
	Owner     string                     `protobuf:"bytes,4,opt,name=owner" json:"owner,omitempty"`
}

func (m *Item) Reset()                    { *m = Item{} }
func (m *Item) String() string            { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()               {}
func (*Item) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Item) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Item) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Item) GetTimestamp() *google_protobuf.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *Item) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

type Items struct {
	Items []*Item `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
}

func (m *Items) Reset()                    { *m = Items{} }
func (m *Items) String() string            { return proto.CompactTextString(m) }
func (*Items) ProtoMessage()               {}
func (*Items) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Items) GetItems() []*Item {
	if m != nil {
		return m.Items
	}
	return nil
}

type KeyIDPair struct {
	Key string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Id  string `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
}

func (m *KeyIDPair) Reset()                    { *m = KeyIDPair{} }
func (m *KeyIDPair) String() string            { return proto.CompactTextString(m) }
func (*KeyIDPair) ProtoMessage()               {}
func (*KeyIDPair) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *KeyIDPair) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *KeyIDPair) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type KeyIDPairs struct {
	KeyIDPairs []*KeyIDPair `protobuf:"bytes,1,rep,name=keyIDPairs" json:"keyIDPairs,omitempty"`
}

func (m *KeyIDPairs) Reset()                    { *m = KeyIDPairs{} }
func (m *KeyIDPairs) String() string            { return proto.CompactTextString(m) }
func (*KeyIDPairs) ProtoMessage()               {}
func (*KeyIDPairs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *KeyIDPairs) GetKeyIDPairs() []*KeyIDPair {
	if m != nil {
		return m.KeyIDPairs
	}
	return nil
}

type StampedKey struct {
	Key       string                     `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Timestamp *google_protobuf.Timestamp `protobuf:"bytes,2,opt,name=timestamp" json:"timestamp,omitempty"`
}

func (m *StampedKey) Reset()                    { *m = StampedKey{} }
func (m *StampedKey) String() string            { return proto.CompactTextString(m) }
func (*StampedKey) ProtoMessage()               {}
func (*StampedKey) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *StampedKey) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *StampedKey) GetTimestamp() *google_protobuf.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

type Index struct {
	BuildTime   *google_protobuf.Timestamp `protobuf:"bytes,1,opt,name=buildTime" json:"buildTime,omitempty"`
	StampedKeys []*StampedKey              `protobuf:"bytes,2,rep,name=stampedKeys" json:"stampedKeys,omitempty"`
}

func (m *Index) Reset()                    { *m = Index{} }
func (m *Index) String() string            { return proto.CompactTextString(m) }
func (*Index) ProtoMessage()               {}
func (*Index) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Index) GetBuildTime() *google_protobuf.Timestamp {
	if m != nil {
		return m.BuildTime
	}
	return nil
}

func (m *Index) GetStampedKeys() []*StampedKey {
	if m != nil {
		return m.StampedKeys
	}
	return nil
}

type IndexMap struct {
	Source  string            `protobuf:"bytes,1,opt,name=source" json:"source,omitempty"`
	Indexes map[string]*Index `protobuf:"bytes,2,rep,name=indexes" json:"indexes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *IndexMap) Reset()                    { *m = IndexMap{} }
func (m *IndexMap) String() string            { return proto.CompactTextString(m) }
func (*IndexMap) ProtoMessage()               {}
func (*IndexMap) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *IndexMap) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *IndexMap) GetIndexes() map[string]*Index {
	if m != nil {
		return m.Indexes
	}
	return nil
}

type DataResponse struct {
	AssociatedBuildTime map[string]*google_protobuf.Timestamp `protobuf:"bytes,1,rep,name=associatedBuildTime" json:"associatedBuildTime,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Items               *Items                                `protobuf:"bytes,2,opt,name=items" json:"items,omitempty"`
}

func (m *DataResponse) Reset()                    { *m = DataResponse{} }
func (m *DataResponse) String() string            { return proto.CompactTextString(m) }
func (*DataResponse) ProtoMessage()               {}
func (*DataResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *DataResponse) GetAssociatedBuildTime() map[string]*google_protobuf.Timestamp {
	if m != nil {
		return m.AssociatedBuildTime
	}
	return nil
}

func (m *DataResponse) GetItems() *Items {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
	proto.RegisterType((*Server)(nil), "model.Server")
	proto.RegisterType((*Item)(nil), "model.Item")
	proto.RegisterType((*Items)(nil), "model.Items")
	proto.RegisterType((*KeyIDPair)(nil), "model.KeyIDPair")
	proto.RegisterType((*KeyIDPairs)(nil), "model.KeyIDPairs")
	proto.RegisterType((*StampedKey)(nil), "model.StampedKey")
	proto.RegisterType((*Index)(nil), "model.Index")
	proto.RegisterType((*IndexMap)(nil), "model.IndexMap")
	proto.RegisterType((*DataResponse)(nil), "model.DataResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Connector service

type ConnectorClient interface {
	Who(ctx context.Context, in *google_protobuf1.Empty, opts ...grpc.CallOption) (*Server, error)
	BackConnect(ctx context.Context, in *Server, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
}

type connectorClient struct {
	cc *grpc.ClientConn
}

func NewConnectorClient(cc *grpc.ClientConn) ConnectorClient {
	return &connectorClient{cc}
}

func (c *connectorClient) Who(ctx context.Context, in *google_protobuf1.Empty, opts ...grpc.CallOption) (*Server, error) {
	out := new(Server)
	err := grpc.Invoke(ctx, "/model.Connector/Who", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectorClient) BackConnect(ctx context.Context, in *Server, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/model.Connector/BackConnect", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Connector service

type ConnectorServer interface {
	Who(context.Context, *google_protobuf1.Empty) (*Server, error)
	BackConnect(context.Context, *Server) (*google_protobuf1.Empty, error)
}

func RegisterConnectorServer(s *grpc.Server, srv ConnectorServer) {
	s.RegisterService(&_Connector_serviceDesc, srv)
}

func _Connector_Who_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf1.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectorServer).Who(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/model.Connector/Who",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectorServer).Who(ctx, req.(*google_protobuf1.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Connector_BackConnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Server)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectorServer).BackConnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/model.Connector/BackConnect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectorServer).BackConnect(ctx, req.(*Server))
	}
	return interceptor(ctx, in, info, handler)
}

var _Connector_serviceDesc = grpc.ServiceDesc{
	ServiceName: "model.Connector",
	HandlerType: (*ConnectorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Who",
			Handler:    _Connector_Who_Handler,
		},
		{
			MethodName: "BackConnect",
			Handler:    _Connector_BackConnect_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "item.proto",
}

// Client API for IndexMapCollector service

type IndexMapCollectorClient interface {
	CollectIndexMap(ctx context.Context, in *IndexMap, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
}

type indexMapCollectorClient struct {
	cc *grpc.ClientConn
}

func NewIndexMapCollectorClient(cc *grpc.ClientConn) IndexMapCollectorClient {
	return &indexMapCollectorClient{cc}
}

func (c *indexMapCollectorClient) CollectIndexMap(ctx context.Context, in *IndexMap, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/model.IndexMapCollector/CollectIndexMap", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for IndexMapCollector service

type IndexMapCollectorServer interface {
	CollectIndexMap(context.Context, *IndexMap) (*google_protobuf1.Empty, error)
}

func RegisterIndexMapCollectorServer(s *grpc.Server, srv IndexMapCollectorServer) {
	s.RegisterService(&_IndexMapCollector_serviceDesc, srv)
}

func _IndexMapCollector_CollectIndexMap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IndexMap)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexMapCollectorServer).CollectIndexMap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/model.IndexMapCollector/CollectIndexMap",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexMapCollectorServer).CollectIndexMap(ctx, req.(*IndexMap))
	}
	return interceptor(ctx, in, info, handler)
}

var _IndexMapCollector_serviceDesc = grpc.ServiceDesc{
	ServiceName: "model.IndexMapCollector",
	HandlerType: (*IndexMapCollectorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CollectIndexMap",
			Handler:    _IndexMapCollector_CollectIndexMap_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "item.proto",
}

// Client API for DataRequest service

type DataRequestClient interface {
	GetData(ctx context.Context, in *KeyIDPairs, opts ...grpc.CallOption) (*DataResponse, error)
}

type dataRequestClient struct {
	cc *grpc.ClientConn
}

func NewDataRequestClient(cc *grpc.ClientConn) DataRequestClient {
	return &dataRequestClient{cc}
}

func (c *dataRequestClient) GetData(ctx context.Context, in *KeyIDPairs, opts ...grpc.CallOption) (*DataResponse, error) {
	out := new(DataResponse)
	err := grpc.Invoke(ctx, "/model.DataRequest/GetData", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for DataRequest service

type DataRequestServer interface {
	GetData(context.Context, *KeyIDPairs) (*DataResponse, error)
}

func RegisterDataRequestServer(s *grpc.Server, srv DataRequestServer) {
	s.RegisterService(&_DataRequest_serviceDesc, srv)
}

func _DataRequest_GetData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyIDPairs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataRequestServer).GetData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/model.DataRequest/GetData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataRequestServer).GetData(ctx, req.(*KeyIDPairs))
	}
	return interceptor(ctx, in, info, handler)
}

var _DataRequest_serviceDesc = grpc.ServiceDesc{
	ServiceName: "model.DataRequest",
	HandlerType: (*DataRequestServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetData",
			Handler:    _DataRequest_GetData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "item.proto",
}

func init() { proto.RegisterFile("item.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 564 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0x4f, 0x6f, 0xd3, 0x4e,
	0x10, 0x95, 0x9d, 0x38, 0xf9, 0x65, 0x9c, 0x1f, 0x6d, 0xb6, 0xa8, 0xb2, 0x0c, 0x12, 0xc1, 0xa7,
	0x08, 0x15, 0xb7, 0xa4, 0x08, 0x55, 0x3d, 0x20, 0xe8, 0x1f, 0x41, 0x54, 0x21, 0x90, 0x8b, 0x04,
	0x27, 0xa4, 0x4d, 0x3c, 0x14, 0x2b, 0xb6, 0x37, 0x78, 0x37, 0x81, 0x48, 0x7c, 0x1c, 0x3e, 0x23,
	0x67, 0xb4, 0xde, 0xb5, 0xe3, 0xa4, 0x0e, 0x88, 0xdb, 0xce, 0xce, 0x9b, 0x37, 0xef, 0xcd, 0xec,
	0x02, 0x44, 0x02, 0x13, 0x7f, 0x96, 0x31, 0xc1, 0x88, 0x95, 0xb0, 0x10, 0x63, 0xf7, 0xc1, 0x0d,
	0x63, 0x37, 0x31, 0x1e, 0xe6, 0x97, 0xe3, 0xf9, 0xe7, 0x43, 0x11, 0x25, 0xc8, 0x05, 0x4d, 0x66,
	0x0a, 0xe7, 0xde, 0xdb, 0x04, 0x60, 0x32, 0x13, 0x4b, 0x95, 0xf4, 0x86, 0xd0, 0xba, 0xc6, 0x6c,
	0x81, 0x19, 0xb9, 0x03, 0x66, 0x14, 0x3a, 0x46, 0xdf, 0x18, 0x74, 0x02, 0x33, 0x0a, 0x89, 0x03,
	0x6d, 0x1a, 0x86, 0x19, 0x72, 0xee, 0x98, 0xf9, 0x65, 0x11, 0x7a, 0x3f, 0xa0, 0x39, 0x12, 0x98,
	0x10, 0x02, 0xcd, 0x90, 0x0a, 0x9a, 0xd7, 0x74, 0x83, 0xfc, 0x4c, 0x76, 0xa1, 0x31, 0xc5, 0xa5,
	0xae, 0x90, 0x47, 0x72, 0x02, 0x9d, 0x52, 0x91, 0xd3, 0xe8, 0x1b, 0x03, 0x7b, 0xe8, 0xfa, 0x4a,
	0x92, 0x5f, 0x48, 0xf2, 0xdf, 0x17, 0x88, 0x60, 0x05, 0x26, 0x77, 0xc1, 0x62, 0xdf, 0x52, 0xcc,
	0x9c, 0x66, 0xce, 0xa6, 0x02, 0xef, 0x11, 0x58, 0xb2, 0x3b, 0x27, 0x0f, 0xc1, 0x92, 0xd3, 0xe0,
	0x8e, 0xd1, 0x6f, 0x0c, 0xec, 0xa1, 0xed, 0xe7, 0xf3, 0xf0, 0x65, 0x32, 0x50, 0x19, 0xef, 0x31,
	0x74, 0xae, 0x70, 0x39, 0xba, 0x78, 0x47, 0xa3, 0xac, 0x90, 0x66, 0xac, 0xa4, 0x29, 0xcb, 0x66,
	0x61, 0xd9, 0x7b, 0x0e, 0x50, 0xc2, 0x39, 0x39, 0x02, 0x98, 0x96, 0x91, 0x6e, 0xb2, 0xab, 0x9b,
	0x94, 0xb0, 0xa0, 0x82, 0xf1, 0x3e, 0x02, 0x5c, 0x4b, 0xe5, 0x18, 0x5e, 0xe1, 0xb2, 0xa6, 0xdf,
	0xda, 0x28, 0xcc, 0x7f, 0x18, 0x85, 0xb7, 0x00, 0x6b, 0x94, 0x86, 0xf8, 0x5d, 0x52, 0x8c, 0xe7,
	0x51, 0x1c, 0x4a, 0x54, 0x4e, 0xfd, 0x17, 0x8a, 0x12, 0x4c, 0x8e, 0xc1, 0xe6, 0xa5, 0x38, 0xb9,
	0x53, 0xe9, 0xa7, 0xa7, 0xfd, 0xac, 0x64, 0x07, 0x55, 0x94, 0xf7, 0xd3, 0x80, 0xff, 0xf2, 0xc6,
	0x6f, 0xe8, 0x8c, 0xec, 0x43, 0x8b, 0xb3, 0x79, 0x36, 0x41, 0xed, 0x49, 0x47, 0xe4, 0x19, 0xb4,
	0x23, 0x89, 0xc1, 0x82, 0xf5, 0x7e, 0xb1, 0x0a, 0x5d, 0xa9, 0x0e, 0xc8, 0x2f, 0x53, 0x91, 0x2d,
	0x83, 0x02, 0xec, 0xbe, 0x86, 0x6e, 0x35, 0x51, 0x33, 0x30, 0x0f, 0xac, 0x05, 0x8d, 0xe7, 0xa8,
	0x87, 0xd5, 0xad, 0xf2, 0x06, 0x2a, 0x75, 0x6a, 0x9e, 0x18, 0xde, 0x2f, 0x03, 0xba, 0x17, 0x54,
	0xd0, 0x00, 0xf9, 0x8c, 0xa5, 0x1c, 0xc9, 0x27, 0xd8, 0xa3, 0x9c, 0xb3, 0x49, 0x44, 0x05, 0x86,
	0x67, 0x95, 0x81, 0x49, 0x79, 0x07, 0x9a, 0xa6, 0x5a, 0xe1, 0xbf, 0xbc, 0x0d, 0x57, 0x72, 0xeb,
	0x88, 0xa4, 0x30, 0xf5, 0xf6, 0x36, 0x84, 0xc9, 0x3b, 0xfd, 0xf8, 0xdc, 0x31, 0x38, 0xdb, 0x48,
	0x6b, 0xac, 0x1e, 0xad, 0x5b, 0xfd, 0xd3, 0x52, 0x57, 0xc6, 0x87, 0x0c, 0x3a, 0xe7, 0x2c, 0x4d,
	0x71, 0x22, 0x58, 0x46, 0x0e, 0xa0, 0xf1, 0xe1, 0x0b, 0x23, 0xfb, 0xb7, 0x4a, 0x2f, 0xe5, 0x87,
	0x77, 0xff, 0x2f, 0x76, 0xad, 0xfe, 0xfb, 0x53, 0xb0, 0xcf, 0xe8, 0x64, 0xaa, 0xcb, 0xc9, 0x7a,
	0xd6, 0xdd, 0x42, 0x32, 0x7c, 0x0b, 0xbd, 0x62, 0xab, 0xe7, 0x2c, 0x8e, 0x55, 0xe3, 0x53, 0xd8,
	0xd1, 0x41, 0xf9, 0x56, 0x76, 0x36, 0x9e, 0xc0, 0x56, 0xc2, 0x17, 0x60, 0xab, 0x3d, 0x7c, 0x9d,
	0x23, 0x17, 0xe4, 0x09, 0xb4, 0x5f, 0xa1, 0x90, 0x37, 0xa4, 0xb7, 0xf9, 0xd7, 0xb8, 0xbb, 0x57,
	0xb3, 0xb9, 0x71, 0x2b, 0x67, 0x3c, 0xfe, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x70, 0x05, 0xa0, 0x77,
	0x1c, 0x05, 0x00, 0x00,
}
